In [2]:
# CarProject 

In [13]:
import pandas as pd
import numpy as np

In [14]:
a = np.array([1,2,3], dtype='int32')
print(a)

[1 2 3]


In [15]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [16]:
a.ndim

1

In [17]:
b.shape

(2, 3)

In [18]:
a.dtype

dtype('int32')

In [19]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [20]:
a[0, 1:-1:2]

array([2, 4, 6])

In [21]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [23]:
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [24]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


In [25]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [26]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [27]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [28]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [29]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])