In [1]:
import numpy as np
import pandas as pd


In [2]:
a=np.array([1,3,4,56,9,65,7])
print(a)

[ 1  3  4 56  9]


In [9]:
print(np.char.replace("He is the best note","He","It"))

It is the best note


In [10]:
a=np.arange(9)
print(a)

[0 1 2 3 4 5 6 7 8]


In [11]:
print("the shape of array")
b=a.reshape(3,3)
print("the shape of range")
print(b)
print("the shape is correct")

the shape of array
the shape of range
[[0 1 2]
 [3 4 5]
 [6 7 8]]
the shape is correct


In [13]:
c=np.arange(16)
print(c)
d=c.reshape(4,4)
print("the modified shape of the array")
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
the modified shape of the array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
